version: '2'

services:
  launchserver:
    image: ijo42/glauncher
    tty: true
    stdin_open: true
    mem_limit: 512mb
    container_name: "launchserver"
    ports:
      - "9274:9274"
    volumes:
      - /home/launchserver/app/:/app/launchserver
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow # Timezone
      - PUID=1001  # User  ID `id $(whoami) -u`
      - PGID=100  # Group ID `id $(whoami) -g`
