version: '2'

services:
  launchserver:
    image: local/launchserver
    tty: true
    stdin_open: true
    mem_limit: 512mb
    container_name: "launchserver"
    hostname: "launchserver"
    ports:
      - "9274:9274"
    volumes:
      - /home/launchserver/modules:/launchserver/modules
      - /home/launchserver/updates:/launchserver/updates
      - /home/launchserver/profiles:/launchserver/profiles
      - /home/launchserver/LaunchServer.json:/launchserver/LaunchServer.json
      - /home/launchserver/config/AutoSaveSession:/launchserver/config/AutoSaveSessions
    restart: always
